#!/bin/bash -l
#PBS -l walltime=1:00:00
#PBS -l mem=16gb

# Pass the cluster argument using -v, e.g:
# qsub install_venv -v cluster=donphan

module load Python/3.12.3-GCCcore-13.3.0

if [ -z $cluster ]; then
	echo "Provide a cluster argument using -v, e.g.: qsub install_venv -v cluster=donphan" 1>&2
	exit 1
fi

VENV_NAME="venv_$cluster"

# Navigate to the source code dir
pushd $VSC_DATA

# Remove old venv if present
if [ -d $VENV_NAME ];
then
	rm -r $VENV_NAME
fi

# Create and activate virtual environment and install packages
python3 -m venv $VENV_NAME
source $VENV_NAME/bin/activate
pip install --no-cache-dir -r $VSC_DATA/nichenetpy/requirements.txt
pip install --no-cache-dir optuna optunahub joblib requests torch scipy memory_profiler
pip install -e $VSC_DATA/nichenetpy