#!/bin/bash -l
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00
#PBS -l mem=80gb

# Pass the cluster argument using -v, for example:
# qsub run_performance.pbs -v cluster=doduo

module load Python/3.12.3-GCCcore-13.3.0

# Navigate to source dir
pushd $VSC_HOME/nichenetpy

# Check for cluster arg
if [ -z $cluster ]; then
	echo "Provide a cluster using -v."
	exit 1
fi

# Name of virtual environment directory
VENV_NAME="venv_$cluster"

# Activate virtual environment
source $VSC_DATA/$VENV_NAME/bin/activate

# Make sure joblib works
unset OMP_PROC_BIND
export OMP_NUM_THREADS=1

ALG="TPE"

# Run the script
python run_optimization.py -c \
    $VSC_DATA/nichenetpy/output/output_test.pkl \
    $VSC_DATA/nichenetpy/model_construction/gr_human_optimization.csv \
    $VSC_DATA/nichenetpy/model_construction/lr_network_human.csv \
    $VSC_DATA/nichenetpy/model_construction/lr_sig_human.csv \
    --settings_file $VSC_DATA/nichenetpy/model_optimization/settings_training_f1234.json \
    --n_trials 160 \
    --n_process 16 \
    --algorithm $ALG \
    --source_path ./source_files \
    --lr_sig_hub 0.115 \
    --gr_hub 0.0803 \
    --ltf_cutoff 0.926 \
    --damping_factor 0.789 \
    --var_database omnipath \
    --id test