#!/bin/bash -l
#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00
#PBS -l mem=230gb

# Pass the cluster argument using -v, for example:
# qsub run_performance.pbs -v cluster=doduo

module load Python/3.12.3-GCCcore-13.3.0

# Navigate to source dir
pushd $VSC_HOME/nichenetpy

# Check for cluster arg
if [ -z $cluster ]; then
	echo "Provide a cluster using -v."
	exit 1
fi

# Name of virtual environment directory
VENV_NAME="venv_$cluster"

# Activate virtual environment
source $VSC_DATA/$VENV_NAME/bin/activate

# Make sure joblib works
unset OMP_PROC_BIND
export OMP_NUM_THREADS=1

ALG="GP"

# Run the script
python run_optimization_v2.py -c \
    "extra_metrics" \
    $VSC_SCRATCH_VO_USER/nichenetpy/model_construction/gr_human_optimization.csv \
    $VSC_SCRATCH_VO_USER/nichenetpy/model_construction/lr_network_human.csv \
    $VSC_SCRATCH_VO_USER/nichenetpy/model_construction/lr_sig_human.csv \
    --settings_file $VSC_SCRATCH_VO_USER/nichenetpy/model_optimization/settings_training_f1234.json \
    --settings_file $VSC_SCRATCH_VO_USER/nichenetpy/model_optimization/settings_training_f1235.json \
    --settings_file $VSC_SCRATCH_VO_USER/nichenetpy/model_optimization/settings_training_f1245.json \
    --settings_file $VSC_SCRATCH_VO_USER/nichenetpy/model_optimization/settings_training_f1345.json \
    --settings_file $VSC_SCRATCH_VO_USER/nichenetpy/model_optimization/settings_training_f2345.json \
    --n_trials 300 \
    --algorithm $ALG \
    --log_dir $VSC_SCRATCH_VO_USER/log \
    --ligand_prediction_evaluation_metric "aupr" \
    --ligand_prediction_evaluation_metric "aupr_corrected" \
    --ligand_prediction_evaluation_metric "auroc" \
    --ligand_prediction_evaluation_metric "pearson" \
    --ligand_prediction_evaluation_metric "map" \
    --ligand_prediction_evaluation_metric "ndcg" \
    --objective_functions "map&ndcg" \
    --metric_score_function "all_geometric_mean"