#!/bin/bash -l
#PBS -l nodes=1:ppn=48
#PBS -l walltime=72:00:00
#PBS -l mem=128gb

# Pass the cluster argument using -v, for example:
# qsub run_performance.pbs -v cluster=doduo

module load Python/3.12.3-GCCcore-13.3.0

# Navigate to source dir
pushd $VSC_HOME/nichenetpy

# Check for cluster arg
if [ -z $cluster ]; then
	echo "Provide a cluster using -v."
	exit 1
fi

# Name of virtual environment directory
VENV_NAME="venv_$cluster"

# Activate virtual environment
source $VENV_NAME/bin/activate

# Make sure joblib works
unset OMP_PROC_BIND
export OMP_NUM_THREADS=1

# Run the script
python run_optimization.py -c \
    $VSC_DATA/nichenetpy/output/output-0.pkl \
    $VSC_DATA/nichenetpy/model_construction/gr_human.csv \
    $VSC_DATA/nichenetpy/model_construction/lr_network_human.csv \
    $VSC_DATA/nichenetpy/model_construction/lr_sig_human.csv \
    --settings_file $VSC_DATA/nichenetpy/model_optimization/settings_training_f1234.json \
    --n_trials 5000 \
    --n_process 48 \
    --algorithm NSGA-II