name: deploy-pypi

# deploy after making e new release
on:
  release:
    types: [published]

  workflow_dispatch: # TODO: delete


# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: install dependencies
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install hatch
      - name: build distribution
        run: |
            hatch build
      - name: Upload distribution
        uses: actions/upload-artifact@v7
        with:
            name: distribution
            path: dist
        
  pypi-publish:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nichenetpy
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download distribution
        uses: actions/download-artifact@v8
        with:
            name: distribution
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            user: __token__
            password: ${{ secrets.NICHENET_API_TOKEN_PYPI }}
            repository-url: https://upload.pypi.org/legacy/